# Generated by Django 3.1.4 on 2020-12-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EntryName', models.CharField(max_length=64)),
                ('Description', models.CharField(max_length=500)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='DataImages')),
            ],
        ),
    ]
